kind: Secret
apiVersion: v1
metadata:
  name: {{ include "docspell.fullname" . }}-joex-config
  labels:
    {{- include "docspell.labels" . | nindent 4 }}
    docspell-component: joex
type: Opaque
data:
  config: {{ (tpl (.Values.joex.config) $) | b64enc }}
