kind: Secret
apiVersion: v1
metadata:
  name: {{ include "docspell.fullname" . }}-restserver-config
  labels:
    {{- include "docspell.labels" . | nindent 4 }}
    docspell-component: restserver
type: Opaque
data:
  config: {{ (tpl (.Values.restserver.config) $) | b64enc }}
