apiVersion: v1
kind: Service
metadata:
  name: {{ include "docspell.fullname" . }}-restserver
  labels:
    {{- include "docspell.labels" . | nindent 4 }}
    docspell-component: restserver
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.restserver.bindPort }}
      targetPort: {{ .Values.restserver.bindPort }}
      protocol: TCP
      name: api
  selector:
    {{- include "docspell.selectorLabels" . | nindent 4 }}
    docspell-component: restserver