apiVersion: v1
kind: Service
metadata:
  name: {{ include "docspell.fullname" . }}-joex
  labels:
    {{- include "docspell.labels" . | nindent 4 }}
    docspell-component: joex
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 7878
      targetPort: 7878
      protocol: TCP
      name: api
  selector:
    {{- include "docspell.selectorLabels" . | nindent 4 }}
    docspell-component: joex